
CREATE TABLE IF NOT EXISTS service_node (  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  service_name
VARCHAR(255) NOT NULL,  owner_team VARCHAR(255),  environment VARCHAR(100),  criticality VARCHAR(50), 
current_slo_target VARCHAR(50),  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS incident_node (  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  service_id BIGINT
REFERENCES service_node(id),  incident_type VARCHAR(255),  severity VARCHAR(50),  detected_at TIMESTAMP,  status
VARCHAR(50),  latency_ms BIGINT,  error_rate DOUBLE PRECISION,  throughput BIGINT,  slo_burn_rate DOUBLE PRECISION, 
customer_impact_score DOUBLE PRECISION,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS root_cause_node (  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  incident_id
BIGINT REFERENCES incident_node(id),  root_cause_type VARCHAR(255),  confidence_score DOUBLE PRECISION,  evidence
TEXT,  detected_by VARCHAR(255),  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS remediation_action_node (  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
incident_id BIGINT REFERENCES incident_node(id),  action_type VARCHAR(255),  tool_name VARCHAR(255),  risk_score
DOUBLE PRECISION,  approval_required BOOLEAN DEFAULT TRUE,  execution_status VARCHAR(50),  rollback_available BOOLEAN
DEFAULT FALSE,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS outcome_node (  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  incident_id BIGINT
REFERENCES incident_node(id),  action_id BIGINT REFERENCES remediation_action_node(id),  success BOOLEAN, 
mttr_seconds BIGINT,  latency_improvement_percent DOUBLE PRECISION,  error_rate_improvement_percent DOUBLE PRECISION, 
rollback_triggered BOOLEAN DEFAULT FALSE,  notes TEXT,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS memory_edge (  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  source_type
VARCHAR(100),  source_id BIGINT,  target_type VARCHAR(100),  target_id BIGINT,  relation_type VARCHAR(100),  weight
DOUBLE PRECISION,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS incident_knowledge (  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  incident_id
BIGINT,  service_name VARCHAR(255),  incident_type VARCHAR(255),  summary TEXT,  root_cause TEXT,  action_taken TEXT, 
outcome TEXT,  embedding TEXT,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS runbook (  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  title VARCHAR(255), 
service_name VARCHAR(255),  incident_type VARCHAR(255),  content TEXT,  recommended_actions TEXT,  risk_notes TEXT, 
embedding TEXT,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS rca_report (  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  incident_id BIGINT, 
root_cause TEXT,  timeline TEXT,  impact TEXT,  resolution TEXT,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

-- Indexes CREATE INDEX IF NOT EXISTS idx_service_name ON service_node(service_name); CREATE INDEX IF NOT EXISTS
idx_incident_type ON incident_node(incident_type); CREATE INDEX IF NOT EXISTS idx_incident_created_at ON
incident_node(created_at); CREATE INDEX IF NOT EXISTS idx_runbook_service ON runbook(service_name);